# This docker-compose file allows you to easily run postgresql
version: '2'
services:
  postgres:
    image: mdillon/postgis:9.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: postgres
    ports:
      - 54320:5432
