# Generated by Django 2.0.10 on 2019-02-03 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableFuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix')),
                ('updated_at', models.DateTimeField(verbose_name='Updated date')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel.Fuel')),
            ],
            options={
                'verbose_name': 'AvailableFuel',
            },
        ),
        migrations.CreateModel(
            name='AvailableService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'AvailableService',
            },
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, verbose_name='Adresse')),
                ('zip', models.CharField(max_length=5, verbose_name='Code Postal')),
                ('city', models.CharField(max_length=128, null=True, verbose_name='Ville')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('updated_at', models.DateTimeField(verbose_name='Updated date')),
            ],
            options={
                'verbose_name': 'Point De Vente',
            },
        ),
        migrations.AddField(
            model_name='availableservice',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Pos'),
        ),
        migrations.AddField(
            model_name='availableservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
        ),
        migrations.AddField(
            model_name='availablefuel',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Pos'),
        ),
    ]
